spring:
  datasource:
    url: jdbc:mysql://${{ secrets.DATABASE_URL }}
    username: ${{ secrets.DATABASE_ID }}
    password: ${{ secrets.DATABASE_PW }}
    driver-class-name: org.mariadb.jdbc.Driver