name: Deploy to Amazon EC2

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: doumi-bucket

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      # (1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # (2) JDK 17 세팅 본인 프로젝트 gradle.build에 있는 자바 버전
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # (3) Gradle build (Test 제외)
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          arguments: clean build -x test

      # (4) AWS 인증 (IAM 사용자 Access Key, Secret Key 활용)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # (5) 빌드 결과물을 S3 버킷에 업로드
      - name: Upload to AWS S3
        run: |
          aws s3 cp $GITHUB_WORKSPACE/build/libs/doumi-web-app.jar s3://$S3_BUCKET_NAME/

      # (6) S3 버킷에서 EC2 인스턴스로 파일 복사
      - name: Copy JAR file to EC2 instance
        run: |
          mkdir -p /path/on/ec2/instance
          sudo chown ec2-user:ec2-user /path/on/ec2/instance
          aws s3 cp s3://$S3_BUCKET_NAME/doumi-web-app.jar /path/on/ec2/instance/
